### ISSUE TITLE
Cannot load datasets

### ISSUE THREAD

**Issue by jgriss** [grisslab/grein_loader#3]
## Description

Loading a dataset (tested with "GSE100040") fails with an error code `500`. This error occurs in >90% of tries.

Tested using the ReactomeGSA datasets deployment, as well as `grein_loader` installed on a fresh python:3.9 docker container.

<details>
<summary>Stack trace</summary>

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/grein_loader/load_dataset.py", line 161, in load_dataset
    description_r.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://www.ilincs.org/apps/grein/session/cf9a5a4196c1d66bc6a5814b57ed1990/dataobj/geo_summary?w=&nonce=rGseESBLxe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/grein_loader/load_dataset.py", line 163, in load_dataset
    LOGGER.error(f"Dataset description for {gse_id} not received: ", err)
Message: 'Dataset description for GSE100040 not received: '
Arguments: (HTTPError('500 Server Error: Internal Server Error for url: http://www.ilincs.org/apps/grein/session/cf9a5a4196c1d66bc6a5814b57ed1990/dataobj/geo_summary?w=&nonce=rGseESBLxe'),)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/grein_loader/load_dataset.py", line 161, in load_dataset
    description_r.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://www.ilincs.org/apps/grein/session/cf9a5a4196c1d66bc6a5814b57ed1990/dataobj/geo_summary?w=&nonce=rGseESBLxe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/grein_loader/load_dataset.py", line 164, in load_dataset
    raise GreinLoaderException(f"Dataset description for {gse_id} not received: ", err)
grein_loader.exceptions.GreinLoaderException: ('Dataset description for GSE100040 not received: ', HTTPError('500 Server Error: Internal Server Error for url: http://www.ilincs.org/apps/grein/session/cf9a5a4196c1d66bc6a5814b57ed1990/dataobj/geo_summary?w=&nonce=rGseESBLxe'))
```
</details>

**Comment by alexgrent** [comment]
The error is related to something like this: 
https://github.com/rstudio/shiny-server/issues/522
