### ISSUE TITLE
Connection to GREIN no longer possible

### ISSUE THREAD

**Issue by jgriss** [grisslab/grein_loader#5]
All connections to GREIN seem to fail with the following error message:

```
Message: 'Streaming error: '
Arguments: (HTTPError('405 Client Error: Method Not Allowed for url: https://www.ilincs.org/apps/grein/__sockjs__/n=GTmpxanwOB/yct/wpKnogPd/xhr_streaming'),)
Traceback (most recent call last):
  File "/home/jg/Projects/derma-bioinf/grein_loader/src/grein_loader/load_overview.py", line 52, in load_overview
    xhr_streaming_r.raise_for_status()
  File "/home/jg/Projects/derma-bioinf/grein_loader/grein_loader.venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://www.ilincs.org/apps/grein/__sockjs__/n=GTmpxanwOB/yct/wpKnogPd/xhr_streaming

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jg/Projects/derma-bioinf/grein_loader/src/grein_loader/load_overview.py", line 55, in load_overview
    raise GreinLoaderException("Streaming error: ", err)
grein_loader.exceptions.GreinLoaderException: ('Streaming error: ', HTTPError('405 Client Error: Method Not Allowed for url: https://www.ilincs.org/apps/grein/__sockjs__/n=GTmpxanwOB/yct/wpKnogPd/xhr_streaming'))
```

**Comment by alexgrent** [comment]
fixed
